#!/bin/sh
### BEGIN INIT INFO
# Provides:		sc-gateway
# Required-Start:	$remote_fs $syslog $networking
# Required-Stop:	$remote_fs $syslog
# Default-Start:	2 3 4 5
# Default-Stop:		1
# Short-Description:	SC-Gateway
### END INIT INFO

set -e 

DESC="SC Gateway server"
PIDFILE=/var/run/sc-gateway.pid
DAEMON=/usr/bin/sc-gateway
NAME=sc-gateway

case "$1" in
  start)
	echo -n "Starting $DESC: "
	start-stop-daemon -S -p $PIDFILE \
	  -x "$DAEMON" -- -d
	echo "$NAME."
	;;
  stop)
	echo -n "Stopping $DESC: "
	start-stop-daemon -K -x "$DAEMON" -p $PIDFILE
	echo "$NAME."
	;;
  restart|force-reload)
	echo -n "Restarting $DESC: "
	start-stop-daemon -K -x "$DAEMON" -p $PIDFILE
	sleep 1
	start-stop-daemon -S -p $PIDFILE \
	  -x "$DAEMON" -- -d
	echo "$NAME."
	;;
  *)
	N=/etc/init.d/$NAME
	echo "Usage: $N {start|stop|restart|force-reload}" >&2
	exit 1
	;;
esac
